global:
  hosts:
    domain: example.com
    externalIP: localhost:8080  # or leave blank if using DNS + ingress controller
certmanager-issuer:
  email: nisrinboukhari19@gmail.com
# optionally disable built-in cert-manager if you already have one or donâ€™t want TLS
# certmanager:
#   install: false
# global:
#   ingress:
#     configureCertmanager: false
